on: 
  push:
    branches:
      - main

jobs:
  trigger:
    name: Trigger
    runs-on: ubuntu-latest

    steps:
      - name: Request
      - run: |
          curl -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" -H "Accept: application/vnd.github.v3+json"  ${{ secrets.BLOG_DISPATCHES_URL }} -d '{"event_type":"update_data"}'
